# Generated by Django 2.0.7 on 2019-05-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_auto_20190527_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='.//<django.db.models.fields.related.ForeignKey>/img'),
        ),
    ]
